### PR TITLE
Ddm 2451 (#1)

### PR DESCRIPTION
**Pull request by cbexson**
Updates to data-publication pages

### CODE REVIEW

**Review by mdunhamwilkie — COMMENTED** [review]
index.md - line 12: as DataBC doesn't exist as an organizational unit anymore, I tried to remember to always write "The DataBC Program" rather than DataBC.  
line 16 - Open Government Licence - British Columbia (c not s)
line 18 - The Province's...

**Review by SteveChapmanBCDX — APPROVED** [review]
@cbexson - I think these changes look great.  I don't have any comments on the content - I'll let the other reviewers deal with those issues.

**Comment by sheilamv** [comment]
> index.md - line 12: as DataBC doesn't exist as an organizational unit anymore, I tried to remember to always write "The DataBC Program" rather than DataBC.
> line 16 - Open Government Licence - British Columbia (c not s)
> line 18 - The Province's...

@mdunhamwilkie , is your reference to line 12 all encompassing in the documentation?  There are many places where DataBC is referenced in the changes noted here.

**Comment by sheilamv** [comment]
There are many places there Licence is spelled with an 's' that should be updated to reflect @mdunhamwilkie 's spelling correction.  @cbexson, will you do a search/replace, or would you like file > line references?

**Pull request merged**
